import type { GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import prisma from '../lib/prisma'
import { AppProps } from 'next/dist/shared/lib/router/router'
import { User } from '../types/User'
import Header from '../components/Header'
// import { Flex, Heading, Input, Button } from '@chakra-ui/react'

export const getStaticProps: GetStaticProps = async () => {
  const users = await prisma.user.findMany({});
  return { props: { users } };
}

const Home = ({ users }: AppProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <Flex height="40vh" alignItems="center" justifyContent="center">
        <Flex direction="column" background="gray.100" p={12} rounded={6}>
          <Heading mb={6}>Log in</Heading>
          <Input placeholder="email@provider.com" variant="filled" mb={3} type="email"/>
          <Input placeholder="********" variant="filled" mb={6} type="password"/>
          <Button colorScheme="teal">Log in</Button>
        </Flex>

      </Flex> */}
      <ul>
        {users ? users.map((user: User) => {
          return <li key={user.id}>{user.email}</li>
        }) : null 
         }
      </ul>
    </div>
  )
}

export default Home
